language: python
python:
  - "3.4"
sudo: false
install:
  - pip install catkin-pkg EmPy PyYAML rosdistro
  - pip install coverage flake8 flake8-docstrings flake8-import-order nose pep8 pyflakes
script:
  - python setup.py nosetests -s --tests test
notifications:
  email: false
